Repository OregonCatholicPress/laravel-lumens-annotations, pull requests merged in 2024-07, with the labels that each got.

#5 Added Illuminate/Support and Illuminate/Console to requirements here.
  composer.json
  composer.lock
Labels: Patch, PR - Small

#6 Add Rector, Run against PHP 8.2 Ruleset
  composer.json
  composer.lock
  rector.php
  src/AnnotationsServiceProvider.php
  src/Console/EventScanCommand.php
  src/Console/RouteScanCommand.php
  src/Events/Generator.php
  src/Metadata/ClassFinder.php
  src/Metadata/EventScanner.php
  src/Metadata/RouteScanner.php
  src/Providers/CommandsServiceProvider.php
  src/Providers/MetadataServiceProvider.php
  src/Routing/Generator.php
Labels: Minor, PR - Small

#7 Updating dependency versions
  composer.json
  composer.lock
  src/AnnotationsServiceProvider.php
  src/Console/EventClearCommand.php
  src/Console/EventScanCommand.php
  src/Console/RouteClearCommand.php
  src/Events/Generator.php
  src/Providers/CommandsServiceProvider.php
Labels: Major
